import {
  ArrowDown,
  ArrowDownRight,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  Bell,
  Bot,
  BookOpen,
  Briefcase,
  Bus,
  Calendar,
  Camera,
  ChartColumn,
  ChevronDown,
  ChevronRight,
  Clock,
  Ellipsis,
  Eye,
  EyeOff,
  Gamepad2,
  Gift,
  Globe,
  GraduationCap,
  House,
  Lightbulb,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Menu,
  Moon,
  Pencil,
  Phone,
  PiggyBank,
  Search,
  Send,
  Settings,
  Shield,
  Sun,
  Target,
  TrendingDown,
  TrendingUp,
  Tv,
  User,
  Utensils,
  Wallet,
  X,
} from "lucide-react";

const ICONS = {
  "arrow-down": ArrowDown,
  "arrow-down-right": ArrowDownRight,
  "arrow-left-right": ArrowLeftRight,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  bell: Bell,
  bot: Bot,
  "book-open": BookOpen,
  briefcase: Briefcase,
  bus: Bus,
  calendar: Calendar,
  camera: Camera,
  "chart-column": ChartColumn,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  clock: Clock,
  ellipsis: Ellipsis,
  eye: Eye,
  "eye-off": EyeOff,
  "gamepad-2": Gamepad2,
  gift: Gift,
  globe: Globe,
  "graduation-cap": GraduationCap,
  house: House,
  lightbulb: Lightbulb,
  lock: Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  mail: Mail,
  menu: Menu,
  moon: Moon,
  pencil: Pencil,
  phone: Phone,
  "piggy-bank": PiggyBank,
  search: Search,
  send: Send,
  settings: Settings,
  shield: Shield,
  sun: Sun,
  target: Target,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  tv: Tv,
  user: User,
  utensils: Utensils,
  wallet: Wallet,
  x: X,
};

export default function Icon({ name, size = 18, className }) {
  const Component = ICONS[name];
  if (!Component) return null;
  return <Component size={size} className={className} strokeWidth={2} aria-hidden="true" />;
}
